apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-chatbot-rag
  namespace: chatbot
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eks-bedrock-chatbot-rag-role"
