apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bedrock-chatbot-enterprise
  namespace: chatbot
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bedrock-chatbot-enterprise
