apiVersion: v1
kind: Service
metadata:
  name: bedrock-chatbot-enterprise
  namespace: chatbot
  labels:
    app: bedrock-chatbot-enterprise
spec:
  selector:
    app: bedrock-chatbot-enterprise
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
