apiVersion: v1
kind: ServiceAccount
metadata:
  name: bedrock-chatbot-enterprise
  namespace: chatbot
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::ACCOUNT_ID:role/eks-bedrock-enterprise-role"
