apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "eks-bedrock-chatbot-connectors.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "eks-bedrock-chatbot-connectors.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleArn | quote }}
