apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai-multi-provider-workspace-gov.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "ai-multi-provider-workspace-gov.labels" . | nindent 4 }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.aws.irsaRoleArn | quote }}
