apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eks-secure-enterprise-api-builder.fullname" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "eks-secure-enterprise-api-builder.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "eks-secure-enterprise-api-builder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "eks-secure-enterprise-api-builder.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: secure-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["python", "workspace/api.py"]
          env:
            - name: AWS_REGION
              value: {{ .Values.aws.region | quote }}
            - name: API_LOG_LEVEL
              value: {{ .Values.app.logLevel | quote }}
          ports:
            - containerPort: {{ .Values.app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.app.port }}
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.app.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
